version: '3.8'

services:
  balanza-service:
    build: .
    container_name: balanza-service
    restart: unless-stopped
    ports:
      - "80:80"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Serial__Puerto=/dev/ttyUSB0
      - Serial__BaudRate=9600
      - Serial__UsaComandoR=true
    volumes:
      - ./appsettings.docker.json:/app/appsettings.json:ro
    privileged: true
